name: 'Decode and export secrets'
description: 'Decodes the keystore and service account secret values and stores them in files in the config directory'

inputs:
  KEYSTORE_BASE64:
    description: 'Keystore base 64'
    required: true
  SERVICE_ACCOUNT_JSON_BASE64:
    description: 'Service account JSON base 64'
    required: true
  working-directory:
    description: 'The working directory for steps in this action'
    required: false
    default: '.'

outputs:
  keystore-file-path:
    description: 'Path of the keystore (relative to the working directory)'
    value: ${{ steps.decode-keystore.outputs.keystore-file-path }}

runs:
  using: "composite"
  steps:
    - name: Create config folder if required
      run: |
        mkdir -p config
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      
    - name: Decode Keystore
      id: decode-keystore
      env:
        ENCODED_STRING: ${{ inputs.KEYSTORE_BASE64 }}
        KEYSTORE_FILE_PATH: config/keystore.jks
      run: |
        echo "${ENCODED_STRING}" | base64 --decode > ${KEYSTORE_FILE_PATH}
        echo "keystore-file-path=${KEYSTORE_FILE_PATH}" >> "$GITHUB_OUTPUT"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Decode Service Account
      env:
        ENCODED_STRING: ${{ inputs.SERVICE_ACCOUNT_JSON_BASE64 }}
      run: |
        echo "${ENCODED_STRING}" | base64 --decode > config/service-account-credentials.json
      shell: bash
      working-directory: ${{ inputs.working-directory }}
