name: 'Decode and export secrets'
description: 'Decodes the keystore and service account secret values and stores them in files in the config directory'

inputs:
  KEYSTORE_BASE64:
    description: 'Keystore base 64'
    required: true
  SERVICE_ACCOUNT_JSON_BASE64:
    description: 'Service account JSON base 64'
    required: true
  working-directory:
    description: 'The working directory for steps in this action'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Create config folder if required
      run: |
        mkdir -p config
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      
    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ inputs.KEYSTORE_BASE64 }}
      run: |
        echo "${ENCODED_STRING}" | base64 --decode > config/keystore.jks
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Decode Service Account
      env:
        ENCODED_STRING: ${{ inputs.SERVICE_ACCOUNT_JSON_BASE64 }}
      run: |
        echo "${ENCODED_STRING}" | base64 --decode > config/service-account-credentials.json
      shell: bash
      working-directory: ${{ inputs.working-directory }}
