name: 'Verify Conventional commit'
description: 'Verify Conventional commit standards against latest git tag'

runs:
  using: "composite"
  steps:
    - name: Install Cocogitto
      uses: cocogitto/cocogitto-action@52d0023b4396897f1815648e553db2ab8d782f3a # v4.2.0
      with:
        command: help # A no-op command

    - name: Verify Conventional commit standards against latest git tag
      run: cog check -l
      shell: bash
