name: 'Verify Conventional commit'
description: 'Verify Conventional commit standards against latest git tag'

runs:
  using: "composite"
  steps:
    - name: Verify Conventional commit standards against latest git tag
      uses: cocogitto/cocogitto-action@ed62593c499c2d7697bb0177213946f1e2634119 #v3
      with:
        check-latest-tag-only: true