name: 'Verify Conventional commit'
description: 'Verify Conventional commit standards against latest git tag'

runs:
  using: "composite"
  steps:
    - name: Install Cocogitto
      uses: cocogitto/cocogitto-action@c7a74f5406bab86da17da0f0e460a69f8219a68c # v3.11
      with:
        check: false

    - name: Verify Conventional commit standards against latest git tag
      run: cog check -l
      shell: bash
