name: 'Upload to sonarcloud (PR)'
description: 'Upload results to sonarcloud'

runs:
  using: "composite"
  steps:
    - name: Upload results to sonarcloud (pull request)
      if: ${{ github.event_name == 'pull_request' }}
      env:
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
      run: |
        ./mobile-android-pipelines/scripts/sonar/scan "PR" ${{ github.head_ref }} ${{ github.event.number }}
      shell: bash