name: 'Increment cog semantic version'
description: 'Increment the release version using Conventional Commits'

outputs:
  current_version:
    description: 'current semantic version'
    value: ${{ steps.versioning.outputs.current_version }}
  new_version:
    description: 'new semantic version'
    value: ${{ steps.versioning.outputs.new_version }}

runs:
  using: "composite"
  steps:
    - name: Increment the release version using Conventional Commits
      id: versioning
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

        current_version=$(cog -v get-version)
        echo "current_version=$current_version" >> $GITHUB_OUTPUT

        cog bump --auto

        new_version=$(cog -v get-version)
        echo "new_version=$new_version" >> $GITHUB_OUTPUT
      shell: bash