name: 'SonarQube Quality Gate check'
description: 'SonarQube Quality Gate check'
inputs:
  sonar-token:
    description: 'Sonar token'
    required: true
  working-directory:
    description: 'The working directory for steps in this action'
    required: true

runs:
  using: "composite"
  steps:
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@d304d050d930b02a896b0f85935344f023928496 # pin@v1.1.0
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      with:
        scanMetadataReportFile: ${{ inputs.working-directory }}/build/sonar/report-task.txt