name: 'SonarQube Quality Gate check'
description: 'SonarQube Quality Gate check'
inputs:
  SONAR_TOKEN:
    description: 'Sonar token'
    required: true
  WORKING_DIRECTORY:
    description: 'The working directory for steps in this action'
    required: true

runs:
  using: "composite"
  steps:
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      if: ${{ github.event_name == 'pull_request' }}
      uses: sonarsource/sonarqube-quality-gate-action@d304d050d930b02a896b0f85935344f023928496 # pin@v1.1.0
      env:
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
      with:
        scanMetadataReportFile: ${{ inputs.WORKING_DIRECTORY }}/build/sonar/report-task.txt