name: 'Android pipelines'
description: 'Run pipelines to validate code before merge and deploy afterwards'
icon: 'check-circle'
color: 'blue'
inputs:
  GITHUB_TOKEN:
    description: 'A GitHub API token that is automatically created by the workflow. This is required for release workflows to upload new release artefacts.'
    required: false
  SONAR_TOKEN:
    description: 'A token for SonarCloud to enable the workflow to read and upload new quality reports.'
    required: true
  VERSION_PREFIX:
    description: 'A prefix added to the Git tag before the app version number'
    default: 'v'
    required: false
  GRADLE_CACHE_DISABLED:
    description: 'Allowing for gradle cache on the runner'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Checkout codebase
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        lfs: 'true'
        submodules: 'true'
        fetch-depth: 0

    - name: Clean workspace
      uses: ./mobile-android-pipelines/actions/clean-workspace

    - name: Setup GitHub Runner workflow
      uses: ./mobile-android-pipelines/actions/setup-runner
      with:
        gradle-cache-disabled: ${{ inputs.GRADLE_CACHE_DISABLED }}
      
    - name: Verify Conventional commit standards against latest git tag
      uses: ./mobile-android-pipelines/actions/verify-conventional-commit
      
    - name: Lint script files
      uses: ./mobile-android-pipelines/actions/lint
    
    - name: Run gradle testing suite
      uses: ./mobile-android-pipelines/actions/run-testing-suite
      
    - name: Sonar scan
      uses: ./mobile-android-pipelines/actions/sonar-scan
      with:
        sonar-token: ${{ inputs.SONAR_TOKEN }}
        
    - name: Bundle reports folder
      uses: ./mobile-android-pipelines/actions/bundle-reports
      
    - name: Increment the release version using Conventional Commits
      id: versioning
      if: ${{ github.event_name != 'pull_request' }}
      uses: ./mobile-android-pipelines/actions/increment-version
      
    - name: Publish release tags
      if: ${{ github.event_name != 'pull_request'
        && steps.versioning.outputs.current_version != steps.versioning.outputs.new_version }}
      uses: ./mobile-android-pipelines/actions/publish-release-tag

    - name: Test local publish
      if: ${{ github.event_name == 'pull_request' }}
      uses: ./mobile-android-pipelines/actions/maven-publish-local

    - name: Publish package
      if: ${{ github.event_name != 'pull_request'
        && steps.versioning.outputs.current_version != steps.versioning.outputs.new_version }}
      uses: ./mobile-android-pipelines/actions/maven-publish
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}

    - name: Generate Changelog
      uses: ./mobile-android-pipelines/actions/generate-and-upload-changelog
      with:
        current-version: ${{ steps.versioning.outputs.current_version }}
        new-version: ${{ steps.versioning.outputs.new_version }}
        version-prefix: ${{ inputs.VERSION_PREFIX }}

    - name: Clean workspace
      uses: ./mobile-android-pipelines/actions/clean-workspace
