name: 'Hotfix setup to instrumentation tests'
description: 'Github actions to verify version and run instrumentation tests'
icon: 'check-circle'
color: 'blue'
inputs:
  GRADLE_CACHE_DISABLED:
    description: 'Allowing for gradle cache on the runner'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Checkout codebase
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        lfs: 'true'
        submodules: 'true'
        fetch-depth: 0

    - name: Clean workspace
      uses: ./mobile-android-pipelines/actions/clean-workspace

    - name: Setup GitHub Runner workflow
      uses: ./mobile-android-pipelines/actions/setup-runner
      with:
        gradle-cache-disabled: ${{ inputs.GRADLE_CACHE_DISABLED }}

    - name: Verify Conventional commit standards against latest hotfix git tag
      id: verify-version
      uses: ./mobile-android-pipelines/actions/get-next-version-from-branch

    - name: Lint script files
      uses: ./mobile-android-pipelines/actions/lint

    - name: Run instrumentation tests
      uses: ./mobile-android-pipelines/actions/run-instrumentation-tests