name: 'Bundle reports'
description: 'Zip and upload buildLogic.plugins.build reports'

runs:
  using: "composite"
  steps:
    - name: Bundle buildLogic.plugins.build reports
      id: bundleReports
      run: |
        zip -9 -r reports.zip **/**/build/reports **/build/reports build/reports
      shell: bash

    - name: Upload buildLogic.plugins.build reports
      id: uploadBuildReports
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: buildLogic.plugins.build-reports
        retention-days: 1
        if-no-files-found: error
        path: |
          reports.zip
