name: 'Bundle reports'
description: 'Zip and upload buildLogic.plugins.build reports'

runs:
  using: "composite"
  steps:
    - name: Bundle buildLogic.plugins.build reports
      id: bundleReports
      run: |
        zip -9 -r reports.zip **/**/build/reports **/build/reports build/reports
      shell: bash

    - name: Upload buildLogic.plugins.build reports
      id: uploadBuildReports
      uses: govuk-one-login/mobile-android-pipelines/actions/upload-artifact@79fc35b19faff39ed49b8ba1fdcd0608760062e1
      with:
        artifact-name: buildLogic.plugins.build-reports
        artifact-path: |
          reports.zip
