name: 'Increment hotfix tag'
description: 'Finds the tag matching the provided version and increments it'

inputs:
  version-name:
    description: 'Version name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create a tag or increment if it already exists then publish it
      run: |
        version_tags=()
        for tag in $(git tag -l '${VERSION-NAME}*')
        do
          version_tags+=( $tag )
        done
        tag_name=""
        version_list_length=${#version_tags[@]}
        if [[ version_list_length==0 ]]
        then
          tag_name="${VERSION-NAME}-fix1"
        else
          latest_tag=version_tags[version_list_length-1]
          current_version=${latest_tag##*fix}
          latest_tag_without_version=${latest_tag%$current_version}
          incremented_version=$((current_version+1))
          tag_name="$latest_tag_without_version$incremented_version"
        fi
        git tag $tag_name
        git push origin $tag_name
      shell: bash
