name: 'Clean workspace'
description: 'Deletes any files retrieved from secrets'

inputs:
  pipelines-directory:
    description: 'Pipelines directory'
    required: false
    default: './mobile-android-pipelines'

runs:
  using: "composite"
  steps:
    - name: Clean workspace
      run: |
        rm -f config/keystore.jks
        rm -f config/service-account.json
      shell: bash

    - name: Stop all emulators
      run: |
        ${PIPELINES_DIRECTORY}/scripts/stopAllEmulators.sh
      env:
        PIPELINES_DIRECTORY: ${{ inputs.pipelines-directory }}
      shell: bash
