name: 'Clean workspace'
description: 'Deletes any files retrieved from secrets'

runs:
  using: "composite"
  steps:
    - name: Clean workspace
      run: |
        rm -f config/keystore.jks
        rm -f config/service-account.json
      shell: bash
    - name: Stop all emulators
      run: |
        ./mobile-android-pipelines/scripts/stopAllEmulators.sh
      shell: bash
