name: 'Run testing suite'
description: 'Run gradle testing suite'
inputs:
  SCREENSHOT_TEST_COMMAND:
    description: 'The paparazzi command(s) needed to run the screenshot tests'
    required: false
  GITHUB_ACTOR:
    description: 'Github username'
    required: false
  GITHUB_TOKEN:
    description: 'Github token'
    required: false

runs:
  using: "composite"
  steps:
    - name: Run instrumentation tests
      run: |
        cd test-project
        ./gradlew allDevicesCheck
      shell: bash

    - name: Upload coverage reports
      uses: ./actions/upload-coverage-reports
      with:
        artifact-name: test-project-instrumentation-test-coverage

    - name: Run screenshot tests
      if: ${{ inputs.SCREENSHOT_TEST_COMMAND != '' }}
      run: |
        ./gradlew ${{ inputs.SCREENSHOT_TEST_COMMAND }} \
        --continue \
        -Pgpr.user=${{ inputs.GITHUB_ACTOR }} \
        -Pgpr.token=${{ inputs.GITHUB_TOKEN }}
      shell: bash

    - name: Run unit tests
      run: |
        cd test-project
        ./gradlew check
      shell: bash

    - name: Upload coverage reports
      uses: ./actions/upload-coverage-reports
      with:
        artifact-name: test-project-unit-test-coverage