name: 'Generate Changelog'
description: 'Generate Changelog'

runs:
  using: "composite"
  steps:
    - name: Generate Changelog
      if: ${{ github.event_name != 'pull_request'
        && steps.versioning.outputs.current_version != steps.versioning.outputs.new_version }}
      run: |
        cog changelog --at v$(cog -v get-version) > CHANGELOG.md
      shell: bash