name: 'Lint'
description: 'Lint files'
inputs:
  scripts-directory:
    description: Directory of bash scripts
    required: true

runs:
  using: "composite"
  steps:
    - name: Lint
      run: |
        ./gradlew \
          vale \
          ktlintCheck \
          detekt \
          lint
      shell: bash