name: 'Hotfix workflow'
description: 'Github actions to verify version and run all tests and reports'

inputs:
  GRADLE_CACHE_DISABLED:
    description: 'Allowing for gradle cache on the runner'
    required: false
    default: 'false'
  SCREENSHOT_TEST_COMMAND:
    description: 'The paparazzi command(s) needed to run the screenshot tests'
    required: false
  PIPELINE_DIRECTORY:
    description: 'The location to run commands from'
    required: false
    default: 'mobile-android-pipelines/'
  TEST_DIRECTORY:
    description: 'The location to run tests and linting from'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Checkout codebase
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        lfs: 'true'
        submodules: 'true'
        fetch-depth: 0

    - name: Clean workspace
      uses: ./${{ inputs.PIPELINE_DIRECTORY }}actions/clean-workspace
      with:
        pipelines-directory: .

    - name: Setup GitHub Runner workflow
      uses: ./${{ inputs.PIPELINE_DIRECTORY }}actions/setup-runner
      with:
        gradle-cache-disabled: ${{ inputs.GRADLE_CACHE_DISABLED }}

    - name: Verify Conventional commit standards against latest hotfix git tag
      id: verify-version
      uses: ./${{ inputs.PIPELINE_DIRECTORY }}actions/get-next-version-from-branch

    - name: Current test location
      if: ${{ inputs.TEST_DIRECTORY != '' }}
      run: |
        cd ${{ inputs.TEST_DIRECTORY }}
      shell: bash

    - name: Lint script files
      uses: ./${{ inputs.PIPELINE_DIRECTORY }}actions/lint

    - name: Run gradle testing suite
      uses: ./${{ inputs.PIPELINE_DIRECTORY }}actions/run-testing-suite
      with:
        SCREENSHOT_TEST_COMMAND: ${{ inputs.SCREENSHOT_TEST_COMMAND }}
        PIPELINE_DIRECTORY: ${{ inputs.PIPELINE_DIRECTORY }}

    - name: Sonar scan
      uses: ./${{ inputs.PIPELINE_DIRECTORY }}actions/sonar-scan
      with:
        sonar-token: ${{ inputs.SONAR_TOKEN }}

    - name: Bundle reports folder
      uses: ./${{ inputs.PIPELINE_DIRECTORY }}actions/bundle-reports

    - name: Test local publish
      uses: ./${{ inputs.PIPELINE_DIRECTORY }}actions/maven-publish-local

    - name: Clean workspace
      uses: ./${{ inputs.PIPELINE_DIRECTORY }}actions/clean-workspace
      with:
        pipelines-directory: .