name: 'Hotfix workflow'
description: 'Github actions to verify version and run all tests and reports'

inputs:
  GRADLE_CACHE_DISABLED:
    description: 'Allowing for gradle cache on the runner'
    required: false
    default: 'false'
  SCREENSHOT_TEST_COMMAND:
    description: 'The paparazzi command(s) needed to run the screenshot tests'
    required: false
  GITHUB_ACTOR:
    description: 'Github username'
    required: false
  GITHUB_TOKEN:
    description: 'Github token'
    required: false
  SONAR_TOKEN:
    description: 'A token for SonarCloud to enable the workflow to read and upload new quality reports.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout codebase
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        lfs: 'true'
        submodules: 'true'
        fetch-depth: 0

    - name: Clean workspace
      uses: ./mobile-android-pipelines/actions/clean-workspace

    - name: Setup GitHub Runner workflow
      uses: ./mobile-android-pipelines/actions/setup-runner
      with:
        gradle-cache-disabled: ${{ inputs.GRADLE_CACHE_DISABLED }}

    - name: Verify Conventional commit standards against latest hotfix git tag
      id: verify-version
      uses: ./mobile-android-pipelines/actions/get-next-version-from-pr-branch

    - name: Lint script files
      uses: ./mobile-android-pipelines/actions/lint

    - name: Run gradle testing suite
      uses: ./mobile-android-pipelines/actions/run-testing-suite
      with:
        SCREENSHOT_TEST_COMMAND: ${{ inputs.SCREENSHOT_TEST_COMMAND }}
        GITHUB_ACTOR: ${{ inputs.GITHUB_ACTOR }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Sonar scan
      uses: ./mobile-android-pipelines/actions/sonar-scan
      with:
        sonar-token: ${{ inputs.SONAR_TOKEN }}

    - name: Bundle reports folder
      uses: ./mobile-android-pipelines/actions/bundle-reports

    - name: Test local publish
      uses: ./mobile-android-pipelines/actions/maven-publish-local

    - name: Clean workspace
      uses: ./mobile-android-pipelines/actions/clean-workspace