name: 'Get next version from commit message'
description: 'Gets the next version number from the release branch when merging into main or hotfix'

outputs:
  next-version:
    description: 'Next version number determined from the commit message'
    value: ${{ steps.get-latest-version-from-commit-msg.outputs.next-version }}

runs:
  using: "composite"
  steps:
    - name: Get latest version from commit message
      id: get-latest-version-from-commit-msg
      # First line of commit must be in a format where the version is the last word and separated
      # by a '/' i.e feat: Merge pull request #662 from govuk-one-authentication/hotfix/1.8.1
      run: |
        commit_title=$(git log -1 --pretty=%s | tail -n1)
        IFS=/ read -ra version_list <<< "$commit_title"
        version_list_length=${#version_list[@]}
        commit_version=${version_list[version_list_length-1]}
        
        if [[ "$commit_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
        then
          NEXT_VERSION="${BASH_REMATCH[0]}"
        else
          echo "Invalid version $commit_version in commit: ($commit_title)"
          exit 1
        fi
        
        tag_version=$(cog -v get-version)
        
        if [[ "$NEXT_VERSION" < "$tag_version" ]]
        then
          echo "Version found in commit message $NEXT_VERSION is smaller than the tagged version $tag_version"
          exit 1
        else
          echo "NEXT_VERSION = $NEXT_VERSION"
          echo "next-version=$NEXT_VERSION" >> $GITHUB_OUTPUT
        fi
      shell: bash
