name: 'Download artifact'

inputs:
  artifact-name:
    description: 'Name of artifact to download'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 #v4.1.8
      with:
        name: ${{ inputs.artifact-name }}
