name: 'Publish the release tag'
description: 'Publish the release tag'

runs:
  using: "composite"
  steps:
    - name: Publish the release
      run: |
        git push --follow-tags && git push --tags
      shell: bash