name: 'Run testing suite'
description: 'Run gradle testing suite'
inputs:
  SCREENSHOT_TEST_COMMAND:
    description: 'The paparazzi command(s) needed to run the screenshot tests'
    required: false

runs:
  using: "composite"
  steps:
    - name: Run instrumentation tests
      run: ./mobile-android-pipelines/scripts/runInstrumentationTests.sh
      shell: bash

    - name: Run screenshot tests
      if: ${{ inputs.SCREENSHOT_TEST_COMMAND != '' }}
      run: |
        ./gradlew ${{ inputs.SCREENSHOT_TEST_COMMAND }} \
        --continue \
        -Pgpr.user=${{ secrets.GITHUB_ACTOR }} \
        -Pgpr.token=${{ secrets.GITHUB_TOKEN }}
      shell: bash

    - name: Run unit tests
      run: ./mobile-android-pipelines/scripts/runUnitTests.sh
      shell: bash