name: 'Bundle app for release'
description: 'Build app for release'
inputs:
  github-actor:
    description: 'Github actor. If not provided, defaults to `github.actor`.'
    required: false
  github-token:
    description: 'Github token'
    required: true
  keystore-file-path:
    description: 'Signing store file path (either absolute or relative to the working directory)'
    required: true
  keystore-password:
    description: 'Signing store password'
    required: true
  keystore-key-alias:
    description: 'Signing key alias'
    required: true
  keystore-key-password:
    description: 'Signing key password'
    required: true
  modules:
    description: 'Modules to be bundled (comma separated without spaces), for example: "app,modules/testWrapper"'
    required: false
    default: 'app'
  flavors:
    description: 'App flavours to be bundled (comma separated without spaces), for example: "staging,production"'
    required: false
  pipelines-directory:
    description: 'Pipelines directory'
    required: false
    default: './mobile-android-pipelines'
  version-code:
    description: 'A unique version code for the build'
    required: true
  version-name:
    description: 'A version name for the build'
    required: false
  working-directory:
    description: 'The working directory for steps in this action'
    required: false
    default: '.'

outputs:
  aab-paths:
    description: 'Paths to build flavor aab files'
    value: ${{ steps.gradle-bundle.outputs.aab-paths }}

runs:
  using: "composite"
  steps:
    - name: Build app for release
      id: gradle-bundle
      run: |
        ${PIPELINES_DIRECTORY}/scripts/bundleRelease.sh
      env:
        GITHUB_ACTOR: ${{ inputs.github-actor || github.actor }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_FLAVORS: ${{ inputs.flavors }}
        MODULES_TO_BUNDLE: ${{ inputs.modules }}
        PIPELINES_DIRECTORY: ${{ inputs.pipelines-directory }}
        SIGNING_KEY_ALIAS: ${{ inputs.keystore-key-alias }}
        SIGNING_KEY_PASSWORD: ${{ inputs.keystore-key-password }}
        SIGNING_STORE_FILE_PATH: ${{ inputs.keystore-file-path }}
        SIGNING_STORE_PASSWORD: ${{ inputs.keystore-password }}
        VERSION_CODE: ${{ inputs.version-code }}
        VERSION_NAME: ${{ inputs.version-name }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
