name: 'Run gradle publish'
description: 'Publish the current build to GitHub Packages'

inputs:
  GITHUB_TOKEN:
    description: 'Service account access token that allows publishing packages'
    required: true
  GITHUB_ACTOR:
    description: 'Service account username that allows publishing packages'
    required: true
  VERSION_NAME:
    description: 'The version name for the build'
    required: false

runs:
  using: "composite"
  steps:
    - name: Publish API package
      id: maven-publish
      run: |
        ./gradlew publish \
          -PversionName="$VERSION_NAME"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ inputs.GITHUB_ACTOR }}
        VERSION_NAME: ${{ inputs.VERSION_NAME }}
