name: 'Upload coverage reports'

inputs:
  artifact-name:
    description: 'Name for the uploaded artifact'
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload coverage reports
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: ${{ inputs.artifact-name }}
        path: "**/reports/jacoco/**/*.xml"
