name: 'Upload coverage reports'

inputs:
  artifact-name:
    description: 'Name for the uploaded artifact'
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload coverage reports
      uses: govuk-one-login/mobile-android-pipelines/actions/upload-artifact@79fc35b19faff39ed49b8ba1fdcd0608760062e1
      with:
        artifact-name: ${{ inputs.artifact-name }}
        artifact-path: "**/reports/jacoco/**/*.xml"
