name: 'Upload coverage reports'

inputs:
  name:
    description: 'Name for the uploaded artifact'
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload coverage reports
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:
        name: ${{ inputs.name }}
        retention-days: 1
        if-no-files-found: error
        path: "**/reports/jacoco/**/*.xml"
