name: 'Upload coverage reports'

inputs:
  artifact-name:
    description: 'Name for the uploaded artifact'
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload coverage reports
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      with:
        name: ${{ inputs.artifact-name }}
        path: "**/reports/jacoco/**/*.xml"
