name: 'Upload coverage reports'

inputs:
  artifact-name:
    description: 'Name for the uploaded artifact'
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload coverage reports
      uses: ./mobile-android-pipelines/actions/upload-artifact
      with:
        artifact-name: ${{ inputs.artifact-name }}
        artifact-path: "**/reports/jacoco/**/*.xml"
