name: 'Scan pull request with Sonar'
description: 'Scan pull request with Sonar and apply the quality gate'

inputs:
  working-directory:
    description: 'The working directory for steps in this action'
    required: false
    default: '.'
  pipelines-directory:
    description: 'The directory where the Android pipelines project is checked out'
    required: false
    default: './mobile-android-pipelines'
  sonar-token:
    description: 'A token for SonarCloud to enable the workflow to read and upload new quality reports.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Scan pull request with Sonar
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        PIPELINES_DIRECTORY: ${{ inputs.pipelines-directory }}
      run: |
        ${PIPELINES_DIRECTORY}/scripts/sonar/scan \
          "PR" \
          ${{ github.head_ref }} \
          ${{ github.event.number }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Check SonarQube Quality Gate
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@d304d050d930b02a896b0f85935344f023928496 # pin@v1.1.0
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      with:
        scanMetadataReportFile: ${{ inputs.working-directory }}/build/sonar/report-task.txt
