name: 'Run SonarCloud Analysis'
description: 'Runs SonarCloud analysis, uploading results and - if analysis type is PR - failing based on analysis result'
inputs:
  sonar-token:
    description: 'A token for SonarCloud to enable the workflow to read and upload new quality reports.'
    required: true
  pipelines-directory:
    description: 'Pipelines directory'
    required: false
    default: './mobile-android-pipelines'
  working-directory:
    description: 'The working directory for steps in this action'
    required: false
    default: '.'


runs:
  using: "composite"
  steps:
    - name: 'Checkout codebase'
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        lfs: 'true'
        fetch-depth: 0

    - name: Setup runner
      uses: ./actions/common-prerequisites

    - name: Download unit test coverage reports
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 #v5.0.0
      with:
        name: test-project-unit-test-coverage

    - name: Download instrumentation test coverage reports
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 #v5.0.0
      with:
        name: test-project-instrumentation-test-coverage

    - name: Bundle reports folder
      uses: ./actions/bundle-reports

    - name: Sonar scan
      uses: ./actions/sonar-scan
      with:
        pipelines-directory: ..
        sonar-token: ${{ inputs.SONAR_TOKEN }}
        working-directory: ./test-project
