name: 'Dependency Submission'
description: 'Generate and submit the dependency graph'

inputs:
  build-root-directory:
    description: 'Path to the root directory of the Gradle project. Defaults to the repository root.'
    required: false
    default: ''
  additional-arguments:
    description: 'Additional arguments to pass to the Gradle dependency submission action'
    required: false
    default: ''
  clear-existing:
    description: 'Clear existing dependency graph before submitting. Defaults to true.'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Clear existing dependency graph
      if: inputs.clear-existing == 'true'
      uses: gradle/actions/dependency-submission/clear@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2
      with:
        build-root-directory: ${{ inputs.build-root-directory }}
        additional-arguments: ${{ inputs.additional-arguments }}
