name: 'Dependency Submission'
description: 'Generate and submit the dependency graph'

inputs:
  build-root-directory:
    description: 'Path to the root directory of the Gradle project. Defaults to the repository root.'
    required: false
    default: ''
  additional-arguments:
    description: 'Additional arguments to pass to the Gradle dependency submission action'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      with:
        build-root-directory: ${{ inputs.build-root-directory }}
        additional-arguments: ${{ inputs.additional-arguments }}
