name: 'Setup Runner'
description: 'Set up GitHub Runner environment for building the Android Modules'
inputs:
  jdk-version:
    description: 'The Java Development Kit (JDK) version to use'
    required: false
    default: '21'
  gradle-version:
    description: 'The version of gradle for the "gradle/gradle-build-action step.'
    required: false
    default: 'wrapper'
  gradle-cache-disabled:
    description: 'Allowing for gradle cache on the runner'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Add path globally
      shell: bash
      run: echo "/usr/local/bin" >> $GITHUB_PATH

    - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        distribution: 'oracle'
        java-version: ${{ inputs.jdk-version }}

    - name: Add JAVA_HOME globally
      env:
        JDK_VERSION: ${{ inputs.jdk-version }}
      run: |
        echo "JAVA_HOME=$(/usr/libexec/java_home --version ${JDK_VERSION})" >> $GITHUB_ENV
      shell: bash

    - name: Set up Homebrew
      id: set-up-homebrew
      # Didn't appear to use versioning!
      uses: Homebrew/actions/setup-homebrew@a7a36215df86859f163fbb774ebe0cecf9ec8547

    - name: Install vale
      run: brew install vale
      shell: bash

    - name: Install cocogitto
      uses: cocogitto/cocogitto-action@390bda87a19bf627e03ad075c67a11e9ddbb7547 # v3.11
      with:
        check: false

    - name: Install KVM hardware acceleration Dependencies
      # see docs: https://help.ubuntu.com/community/KVM/Installation
      run: |
        sudo apt-get update
        sudo apt-get install \
          qemu-kvm \
          libvirt-daemon-system \
          libvirt-clients \
          bridge-utils
      shell: bash
      if: runner.os == 'Linux'

# https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/
    - name: Configure KVM hardware acceleration
      run:
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
      shell: bash
      if: runner.os == 'Linux'

    - name: Modify KVM groups / rules
      run: |
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
        sudo adduser $(id -un) libvirt
        sudo adduser $(id -un) kvm
      shell: bash
      if: runner.os == 'Linux'

    - name: Confirm KVM hardware acceleration is installed
      run: |
        kvm-ok
        egrep --count '(vmx|svm)' /proc/cpuinfo
      shell: bash
      if: runner.os == 'Linux'

    - name: Setup Gradle
      id: setupGradle
      uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
      with:
        gradle-version: ${{ inputs.gradle-version }}
        cache-disabled: ${{ inputs.gradle-cache-disabled == 'true' }}

    - name: Setup Android SDK
      uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407 # v3.2.2

    - name: Update Android SDK Manager
      run: |
        sdkmanager --update
      shell: bash
