name: 'Setup Runner'
description: 'Set up GitHub Runner environment for building the Android Modules'
inputs:
  jdk-version:
    description: 'The Java Development Kit (JDK) version to use'
    required: false
    default: '21'
  gradle-version:
    description: 'The version of gradle for the "gradle/gradle-build-action step.'
    required: false
    default: 'wrapper'
  gradle-cache-disabled:
    description: 'Allowing for gradle cache on the runner'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Add path globally
      shell: bash
      run: echo "/usr/local/bin" >> $GITHUB_PATH

    - name: Set up JDK ${{ inputs.jdk-version }}
      shell: bash
      run: |
        JAVA_HOME_VAR="JAVA_HOME_${{ inputs.jdk-version }}_X64"
        echo "JAVA_HOME=${!JAVA_HOME_VAR}" >> $GITHUB_ENV
        echo "${!JAVA_HOME_VAR}/bin" >> $GITHUB_PATH

    - name: Set up Homebrew
      shell: bash
      run: |
        echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
        echo "/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

    - name: Install cocogitto
      uses: cocogitto/cocogitto-action@52d0023b4396897f1815648e553db2ab8d782f3a # v4.2.0
      with:
        command: help # A no-op command

    - name: Install KVM hardware acceleration Dependencies
      # see docs: https://help.ubuntu.com/community/KVM/Installation
      run: |
        sudo apt-get update
        sudo apt-get install \
          qemu-kvm \
          libvirt-daemon-system \
          libvirt-clients \
          bridge-utils
      shell: bash
      if: runner.os == 'Linux'

# https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/
    - name: Configure KVM hardware acceleration
      run:
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
      shell: bash
      if: runner.os == 'Linux'

    - name: Modify KVM groups / rules
      run: |
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
        sudo adduser $(id -un) libvirt
        sudo adduser $(id -un) kvm
      shell: bash
      if: runner.os == 'Linux'

    - name: Confirm KVM hardware acceleration is installed
      run: |
        kvm-ok
        egrep --count '(vmx|svm)' /proc/cpuinfo
      shell: bash
      if: runner.os == 'Linux'

    - name: Setup Gradle
      id: setupGradle
      uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      with:
        gradle-version: ${{ inputs.gradle-version }}
        cache-disabled: ${{ inputs.gradle-cache-disabled == 'true' }}
        cache-provider: basic

    - name: Setup Android SDK
      uses: android-actions/setup-android@40fd30fb8d7440372e1316f5d1809ec01dcd3699 # v4.0.1
