name: 'Scan and Quality Gate with Sonar'
description: 'Scan with Sonar and apply the quality gate'

inputs:
  working-directory:
    description: 'The working directory for steps in this action'
    required: false
    default: '.'
  pipelines-directory:
    description: 'The directory where the Android pipelines project is checked out'
    required: false
    default: './mobile-android-pipelines'
  sonar-token:
    description: 'A token for SonarCloud to enable the workflow to read and upload new quality reports.'
    required: true
  analysis-type:
    description: 'Sonar scan analysis type: PR, BRANCH or LOCAL'
    required: true

runs:
  using: "composite"
  steps:
    - name: Scan pull request with Sonar
      uses: ${{ inputs.pipelines-directory }}/actions/sonar-scan
      with:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        ANALYSIS_TYPE: ${{ inputs.analysis-type }}

    - name: Check SonarQube Quality Gate
      id: sonarqube-quality-gate-check
      uses: ${{ inputs.pipelines-directory }}/actions/sonar-quality-gate
      with:
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}
