name: 'Hotfix setup to instrumentation tests'
description: 'Github actions to verify version and run instrumentation tests'

inputs:
  GITHUB_TOKEN:
    description: 'A GitHub API token that is automatically created by the workflow. This is required for release workflows to upload new release artefacts.'
    required: false
  SCREENSHOT_TEST_COMMAND:
    description: 'The paparazzi command(s) needed to run the screenshot tests'
    required: false
  SONAR_TOKEN:
    description: 'A token for SonarCloud to enable the workflow to read and upload new quality reports.'
    required: true
  VERSION_PREFIX:
    description: 'A prefix added to the Git tag before the app version number'
    default: 'v'
    required: false
  GITHUB_ACTOR:
    description: 'Github username'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout codebase
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        lfs: 'true'
        submodules: 'true'
        fetch-depth: 0

    - name: Clean workspace
      uses: ./mobile-android-pipelines/actions/clean-workspace

    - name: Setup GitHub Runner workflow
      uses: ./mobile-android-pipelines/actions/setup-runner
      with:
        gradle-cache-disabled: ${{ inputs.GRADLE_CACHE_DISABLED }}

    - name: Verify Conventional commit standards against latest hotfix git tag
      id: verify-version
      uses: ./mobile-android-pipelines/actions/get-next-version-from-commit-message

    - name: Increment and push hotfix git tag
      id: create-tag-and-increment
      uses: ./mobile-android-pipelines/actions/increment-hotfix-tag
      with:
        version-name: ${{ steps.verify-version.outputs.next-version }}

    - name: Lint script files
      uses: ./mobile-android-pipelines/actions/lint

    - name: Run gradle testing suite
      uses: ./mobile-android-pipelines/actions/run-testing-suite
      with:
        SCREENSHOT_TEST_COMMAND: ${{ inputs.SCREENSHOT_TEST_COMMAND }}
        GITHUB_ACTOR: ${{ inputs.GITHUB_ACTOR }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Sonar scan
      uses: ./mobile-android-pipelines/actions/sonar-scan
      with:
        sonar-token: ${{ inputs.SONAR_TOKEN }}
        version-name: ${{ steps.create-tag-and-increment.outputs.incremented-version }}

    - name: Bundle reports folder
      uses: ./mobile-android-pipelines/actions/bundle-reports

    - name: Test local publish
      uses: ./mobile-android-pipelines/actions/maven-publish-local
      with:
        version-name: ${{ steps.create-tag-and-increment.outputs.incremented-version }}

    - name: Publish package
      uses: ./mobile-android-pipelines/actions/maven-publish
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
        VERSION_NAME: ${{ steps.create-tag-and-increment.outputs.incremented-version }}

    - name: Delete hotfix branch
      uses: ./mobile-android-pipelines/actions/delete-hotfix-branch

    - name: Clean workspace
      uses: ./mobile-android-pipelines/actions/clean-workspace
