name: 'Install Vale'
description: 'Install Vale using Homebrew with caching.'
runs:
  using: "composite"
  steps:
    - name: Set Github Action path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Get latest Vale version
      id: vale-version
      run: |
        version=$(vale_version.bash)
        echo "Vale version: $version" >&2
        echo "version=$version" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Get Homebrew path prefix
      id: brew-path
      run: |
        prefix=$(brew --prefix)
        echo "Homebrew path prefix: $prefix" >&2
        echo "prefix=$prefix" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Cache Vale
      id: cache-vale
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: |
          ${{ steps.brew-path.outputs.prefix }}/Cellar/vale
          ${{ steps.brew-path.outputs.prefix }}/bin/vale
          ${{ steps.brew-path.outputs.prefix }}/opt/vale
        key: vale-${{ runner.os }}-${{ steps.vale-version.outputs.version }}

    - name: Install Vale
      if: steps.cache-vale.outputs.cache-hit != 'true'
      run: brew install vale
      shell: bash
