name: 'Upload to sonarcloud (merge)'
description: 'Upload results to sonarcloud'

runs:
  using: "composite"
  steps:
    - name: Upload results to sonarcloud
      if: ${{ github.event_name != 'pull_request' }}
      env:
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
      run: |
        ./mobile-android-pipelines/scripts/sonar/scan "BRANCH" ${{ github.ref_name }}
      shell: bash