name: 'Lint and test files'
description: 'Lint and test files via script'
inputs:
  TEST_RUNNER_MODE:
    description: 'unit, instrumentation, both'
    required: false
    default: 'both'
  SHOULD_RUN_DEPENDENCY_CHECKER:
    description: 'Provide any value if you want to run the OWASP dependency checker'
    required: false

runs:
  using: "composite"
  steps:
    - name: Lint script files
      env:
        TEST_RUNNER_MODE: ${{ inputs.TEST_RUNNER_MODE }}
        DEPENDENCY_CHECK: ${{ inputs.SHOULD_RUN_DEPENDENCY_CHECKER }}
      run: ./mobile-android-pipelines/scripts/lintAndTestProject.sh "${TEST_RUNNER_MODE}" "${DEPENDENCY_CHECK}"
      shell: bash