name: 'Generate and Upload Changelog'
description: 'Generate and Upload Changelog'
inputs:
  CURRENT_VERSION:
    description: 'current semantic version'
    required: true
  NEW_VERSION:
    description: 'new semantic version'
    required: true
  VERSION_PREFIX:
    description: 'A prefix added to the Git tag before the app version number'
    default: 'v'
    required: false

runs:
  using: "composite"
  steps:
    - name: Generate Changelog
      if: ${{ inputs.CURRENT_VERSION != inputs.NEW_VERSION }}
      run: |
        cog changelog --at ${VERSION_PREFIX}$(cog -v get-version) > CHANGELOG.md
      env:
        VERSION_PREFIX: ${{ inputs.VERSION_PREFIX }}
      shell: bash

    - name: Upload Changelog
      if: ${{ inputs.CURRENT_VERSION != inputs.NEW_VERSION }}
      id: uploadBuildReports
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:
        name: CHANGELOG.md
        path: |
          CHANGELOG.md
