name: 'Generate and Upload Changelog'
description: 'Generate and Upload Changelog'
inputs:
  CURRENT_VERSION:
    description: 'current semantic version'
    required: true
  NEW_VERSION:
    description: 'new semantic version'
    required: true
  VERSION_PREFIX:
    description: 'version prefix'
    required: false

runs:
  using: "composite"
  steps:
    - name: Generate Changelog
      if: ${{ inputs.CURRENT_VERSION != inputs.NEW_VERSION }}
      run: |
        cog changelog --at ${VERSION_PREFIX}$(cog -v get-version) > CHANGELOG.md
      env:
        VERSION_PREFIX: ${{ inputs.VERSION_PREFIX }}
      shell: bash

    - name: Upload Changelog
      if: ${{ inputs.CURRENT_VERSION != inputs.NEW_VERSION }}
      id: uploadBuildReports
      uses: ./mobile-android-pipelines/actions/upload-artifact
      with:
        artifact-name: CHANGELOG.md
        artifact-path: |
          CHANGELOG.md