name: On Pull Request (develop/release/main)

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-scripts:
    name: Check scripts
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout codebase'
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Lint scripts
        run: |
          # Lint all files in the .sh folder / sub-folders
          find ./scripts -type f -exec shellcheck {} +

  check-build-logic:
    name: Check build logic
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout codebase'
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Lint build logic
        run: |
          cd buildLogic
          ./gradlew \
            :plugins:detekt \
            :plugins:ktlintCheck

  check-test-project:
    name: Check test project
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout codebase'
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Setup runner
        uses: ./actions/setup-runner
        with:
          jdk-version: 21

      - name: Check test project
        run: |
          cd test-project
          ./gradlew check

      - name: Run test project instrumentation tests
        run: |
          cd test-project
          ./gradlew googleAtdPixelXLApi33Check

