name: 'Prerequisites'
description: 'Set up GitHub Runner environment for building the Android Modules'
inputs:
  jdk-version:
    description: 'The Java Development Kit (JDK) version to use'
    required: false
    default: '21'
  install-vale:
    description: 'Install vale prose linter'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.jdk-version }}
      shell: bash
      run: |
        JAVA_HOME_VAR="JAVA_HOME_${{ inputs.jdk-version }}_X64"
        echo "JAVA_HOME=${!JAVA_HOME_VAR}" >> $GITHUB_ENV
        echo "${!JAVA_HOME_VAR}/bin" >> $GITHUB_PATH

    - name: Install Cocogitto
      uses: cocogitto/cocogitto-action@52d0023b4396897f1815648e553db2ab8d782f3a # v4.2.0
      with:
        command: help # A no-op command

    - name: Set up Homebrew
      shell: bash
      run: |
        echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
        echo "/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

    - name: Install Vale
      if: inputs.install-vale == 'true'
      run: brew install vale
      shell: bash
