name: 'Prerequisites'
description: 'Set up GitHub Runner environment for building the Android Modules'
inputs:
  jdk-version:
    description: 'The Java Development Kit (JDK) version to use'
    required: false
    default: '21'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        distribution: 'oracle'
        java-version: ${{ inputs.jdk-version }}
        cache: gradle

    - name: Install Cocogitto
      uses: cocogitto/cocogitto-action@c7a74f5406bab86da17da0f0e460a69f8219a68c # v3.11
      with:
        check: false

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install Vale
      run: brew install vale
      shell: bash
