name: 'Prerequisites'
description: 'Set up GitHub Runner environment for building the Android Modules'
inputs:
  jdk-version:
    description: 'The Java Development Kit (JDK) version to use'
    required: false
    default: '21'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        distribution: 'oracle'
        java-version: ${{ inputs.jdk-version }}
        cache: gradle

    - name: Install Cocogitto
      uses: cocogitto/cocogitto-action@390bda87a19bf627e03ad075c67a11e9ddbb7547 # v3.11
      with:
        check: false

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install Vale
      run: brew install vale
      shell: bash
